// AUTO-GENERATED by scripts/build-animals.mjs — do not edit by hand.
// Curated recognizable mammals sourced from the EOL/PanTHERIA archive
// (animal database/archive/taxon.tab). 63 species.

export interface Animal {
  name: string;
  emoji: string;
  scientificName: string;
}

export const ANIMALS: Animal[] = [
  {
    "name": "African Elephant",
    "emoji": "🐘",
    "scientificName": "Loxodonta africana"
  },
  {
    "name": "American Bison",
    "emoji": "🦬",
    "scientificName": "Bison bison"
  },
  {
    "name": "Asian Elephant",
    "emoji": "🐘",
    "scientificName": "Elephas maximus"
  },
  {
    "name": "Bactrian Camel",
    "emoji": "🐫",
    "scientificName": "Camelus bactrianus"
  },
  {
    "name": "Badger",
    "emoji": "🦡",
    "scientificName": "Meles meles"
  },
  {
    "name": "Beaver",
    "emoji": "🦫",
    "scientificName": "Castor canadensis"
  },
  {
    "name": "Bighorn Sheep",
    "emoji": "🐏",
    "scientificName": "Ovis canadensis"
  },
  {
    "name": "Black Rhinoceros",
    "emoji": "🦏",
    "scientificName": "Diceros bicornis"
  },
  {
    "name": "Blue Whale",
    "emoji": "🐋",
    "scientificName": "Balaenoptera musculus"
  },
  {
    "name": "Bottlenose Dolphin",
    "emoji": "🐬",
    "scientificName": "Tursiops truncatus"
  },
  {
    "name": "Brown Bear",
    "emoji": "🐻",
    "scientificName": "Ursus arctos"
  },
  {
    "name": "Brown Hare",
    "emoji": "🐇",
    "scientificName": "Lepus europaeus"
  },
  {
    "name": "Brown Rat",
    "emoji": "🐀",
    "scientificName": "Rattus norvegicus"
  },
  {
    "name": "Brown-throated Sloth",
    "emoji": "🦥",
    "scientificName": "Bradypus variegatus"
  },
  {
    "name": "Cattle",
    "emoji": "🐄",
    "scientificName": "Bos taurus"
  },
  {
    "name": "Cheetah",
    "emoji": "🐆",
    "scientificName": "Acinonyx jubatus"
  },
  {
    "name": "Chimpanzee",
    "emoji": "🐒",
    "scientificName": "Pan troglodytes"
  },
  {
    "name": "Common Dolphin",
    "emoji": "🐬",
    "scientificName": "Delphinus delphis"
  },
  {
    "name": "Coyote",
    "emoji": "🐺",
    "scientificName": "Canis latrans"
  },
  {
    "name": "Donkey",
    "emoji": "🫏",
    "scientificName": "Equus asinus"
  },
  {
    "name": "Dromedary Camel",
    "emoji": "🐪",
    "scientificName": "Camelus dromedarius"
  },
  {
    "name": "Eastern Grey Kangaroo",
    "emoji": "🦘",
    "scientificName": "Macropus giganteus"
  },
  {
    "name": "Eurasian Beaver",
    "emoji": "🦫",
    "scientificName": "Castor fiber"
  },
  {
    "name": "Giant Panda",
    "emoji": "🐼",
    "scientificName": "Ailuropoda melanoleuca"
  },
  {
    "name": "Giraffe",
    "emoji": "🦒",
    "scientificName": "Giraffa camelopardalis"
  },
  {
    "name": "Goat",
    "emoji": "🐐",
    "scientificName": "Capra hircus"
  },
  {
    "name": "Gorilla",
    "emoji": "🦍",
    "scientificName": "Gorilla gorilla"
  },
  {
    "name": "Grévy's Zebra",
    "emoji": "🦓",
    "scientificName": "Equus grevyi"
  },
  {
    "name": "Grey Squirrel",
    "emoji": "🐿️",
    "scientificName": "Sciurus carolinensis"
  },
  {
    "name": "Hedgehog",
    "emoji": "🦔",
    "scientificName": "Erinaceus europaeus"
  },
  {
    "name": "Hippopotamus",
    "emoji": "🦛",
    "scientificName": "Hippopotamus amphibius"
  },
  {
    "name": "Horse",
    "emoji": "🐴",
    "scientificName": "Equus caballus"
  },
  {
    "name": "House Mouse",
    "emoji": "🐁",
    "scientificName": "Mus musculus"
  },
  {
    "name": "Humpback Whale",
    "emoji": "🐋",
    "scientificName": "Megaptera novaeangliae"
  },
  {
    "name": "Indian Rhinoceros",
    "emoji": "🦏",
    "scientificName": "Rhinoceros unicornis"
  },
  {
    "name": "Jaguar",
    "emoji": "🐆",
    "scientificName": "Panthera onca"
  },
  {
    "name": "Koala",
    "emoji": "🐨",
    "scientificName": "Phascolarctos cinereus"
  },
  {
    "name": "Leopard",
    "emoji": "🐆",
    "scientificName": "Panthera pardus"
  },
  {
    "name": "Lion",
    "emoji": "🦁",
    "scientificName": "Panthera leo"
  },
  {
    "name": "Llama",
    "emoji": "🦙",
    "scientificName": "Lama glama"
  },
  {
    "name": "Moose",
    "emoji": "🫎",
    "scientificName": "Alces alces"
  },
  {
    "name": "Orangutan",
    "emoji": "🦧",
    "scientificName": "Pongo pygmaeus"
  },
  {
    "name": "Orca",
    "emoji": "🐋",
    "scientificName": "Orcinus orca"
  },
  {
    "name": "Otter",
    "emoji": "🦦",
    "scientificName": "Lutra lutra"
  },
  {
    "name": "Pale-throated Sloth",
    "emoji": "🦥",
    "scientificName": "Bradypus tridactylus"
  },
  {
    "name": "Polar Bear",
    "emoji": "🐻‍❄️",
    "scientificName": "Ursus maritimus"
  },
  {
    "name": "Rabbit",
    "emoji": "🐰",
    "scientificName": "Oryctolagus cuniculus"
  },
  {
    "name": "Raccoon",
    "emoji": "🦝",
    "scientificName": "Procyon lotor"
  },
  {
    "name": "Red Deer",
    "emoji": "🦌",
    "scientificName": "Cervus elaphus"
  },
  {
    "name": "Red Fox",
    "emoji": "🦊",
    "scientificName": "Vulpes vulpes"
  },
  {
    "name": "Red Kangaroo",
    "emoji": "🦘",
    "scientificName": "Macropus rufus"
  },
  {
    "name": "Red Squirrel",
    "emoji": "🐿️",
    "scientificName": "Sciurus vulgaris"
  },
  {
    "name": "Reindeer",
    "emoji": "🦌",
    "scientificName": "Rangifer tarandus"
  },
  {
    "name": "Sheep",
    "emoji": "🐑",
    "scientificName": "Ovis aries"
  },
  {
    "name": "Skunk",
    "emoji": "🦨",
    "scientificName": "Mephitis mephitis"
  },
  {
    "name": "Tiger",
    "emoji": "🐯",
    "scientificName": "Panthera tigris"
  },
  {
    "name": "Water Buffalo",
    "emoji": "🐃",
    "scientificName": "Bubalus bubalis"
  },
  {
    "name": "White Rhinoceros",
    "emoji": "🦏",
    "scientificName": "Ceratotherium simum"
  },
  {
    "name": "White-tailed Deer",
    "emoji": "🦌",
    "scientificName": "Odocoileus virginianus"
  },
  {
    "name": "Wild Boar",
    "emoji": "🐗",
    "scientificName": "Sus scrofa"
  },
  {
    "name": "Wildcat",
    "emoji": "🐱",
    "scientificName": "Felis silvestris"
  },
  {
    "name": "Wolf",
    "emoji": "🐺",
    "scientificName": "Canis lupus"
  },
  {
    "name": "Zebra",
    "emoji": "🦓",
    "scientificName": "Equus zebra"
  }
];

/** Pick a random celebratory animal for the finish screen. */
export function randomAnimal(): Animal {
  return ANIMALS[Math.floor(Math.random() * ANIMALS.length)];
}
